const steps=[
{id:'urgency',title:'臨床症狀與急迫性',short:'症狀',desc:'先判斷是否需要立即處理。嚴重神經症狀時，治療優先於完整鑑別。',hints:['嚴重症狀：癲癇、昏迷、GCS <= 8、嚴重嗜睡、心肺窘迫。','中度症狀：噁心無嘔吐、頭痛、意識混亂、步態不穩。','急性 <48 小時；若時間不明，通常先視為慢性以降低 ODS 風險。'],fields:[['age','年齡','number',1,['歲']],['sex','性別','select',1,['女性','男性','其他/不明']],['onset','低血鈉發生時間','select',1,['<48 小時','>=48 小時','不明']],['symptomSeverity','症狀嚴重度','select',1,['無症狀/輕微','中度症狀','嚴重症狀']],['symptoms','具體症狀','checks',1,['噁心','嘔吐','頭痛','混亂','嗜睡','癲癇','昏迷','心肺窘迫','肌肉痙攣','無明顯症狀'],1],['initialNote','其他臨床背景','textarea',0,['可填入癌症、CNS 疾病、肺部疾病、近期手術、疼痛、噁心、運動、住院背景。'],1]]},
{id:'confirm',title:'確認低血鈉與排除非低張性原因',short:'確認',desc:'用血鈉、血糖與血清滲透壓確認是否為真正的低張性低血鈉。',hints:['先排除高血糖、甘露醇、IVIG、TURP/hysteroscopy irrigant、嚴重高脂血症或高蛋白血症。','校正鈉估算：Na + 2.4 x ((glucose - 100) / 100)。','Serum osmolality >=275 mOsm/kg 時，優先考慮非低張性或偽性低血鈉。'],fields:[['serumNa','血清鈉 Na','number',1,['mEq/L']],['glucose','血糖','number',1,['mg/dL']],['serumOsm','實測血清滲透壓','number',1,['mOsm/kg']],['pseudoRisk','偽性/非低張性線索','checks',1,['無','高脂血症','高蛋白血症','高血糖','mannitol','IVIG','TURP/子宮鏡沖洗液','造影/其他滲透物'],1]]},
{id:'urine',title:'尿液滲透壓與水排除能力',short:'尿滲透壓',desc:'確認腎臟是否能適當排出稀釋尿，將低溶質/多喝水與 AVP 相關狀態分開。',hints:['Urine osmolality <=100：考慮 primary polydipsia、beer potomania、tea and toast diet。','Urine osmolality >100：表示尿液不適當濃縮，需要進一步看尿鈉與體液狀態。','急性或嚴重症狀時，治療與監測可與診斷同步進行。'],fields:[['urineOsm','尿液滲透壓','number',1,['mOsm/kg']],['fluidIntake','水分/低溶質攝取線索','checks',1,['無','大量飲水','精神性多喝水','耐力運動','MDMA/ecstasy','啤酒大量攝取','低蛋白低鹽飲食','營養不良'],1]]},
{id:'volume',title:'尿鈉與體液狀態鑑別',short:'體液狀態',desc:'用尿鈉、有效循環量與水腫狀態定位為低容積、等容積或高容積低血鈉。',hints:['Urine Na <=30：常見於低有效動脈血量，如 HF、肝硬化、腎病症候群、嘔吐腹瀉、第三空間。','Urine Na >30：需評估利尿劑、腎臟病、adrenal insufficiency、SIADH、CSW。','SIADH 通常等容積；CSW 通常低容積且需補液補鹽。'],fields:[['urineNa','尿鈉','number',1,['mmol/L']],['volumeStatus','臨床體液狀態','select',1,['低容積','等容積','高容積/水腫','不確定']],['edemaSigns','水腫/低有效循環線索','checks',1,['無','心衰竭','肝硬化/腹水','腎病症候群','腎衰竭','下肢水腫','肺水腫'],1],['lossSigns','體液或鈉流失線索','checks',1,['無','嘔吐','腹瀉','流汗/燒傷','胰臟炎/第三空間','近期利尿劑','腦部疾病後疑 CSW'],1]]},
{id:'etiology',title:'病因確認：內分泌、用藥、影像與共病',short:'病因',desc:'補齊 SIADH 排除條件、藥物與影像線索，避免把可逆原因誤判為 SIADH。',hints:['SIADH 是排除性診斷：需排除 adrenal insufficiency、severe hypothyroidism、renal failure、近期利尿劑。','常見誘因：惡性腫瘤、CNS 疾病、肺部感染、SSRI、carbamazepine、cyclophosphamide、desmopressin。','影像/病史資料可協助找出 CNS、肺部或腫瘤相關病因。'],fields:[['kidneyFunction','腎功能','select',1,['正常/接近正常','AKI','CKD 3-5','不明']],['thyroid','甲狀腺功能','select',1,['已排除嚴重低下','疑似/確認嚴重低下','尚未檢查']],['adrenal','腎上腺/皮質醇狀態','select',1,['已排除 adrenal insufficiency','疑似/確認 adrenal insufficiency','尚未檢查']],['diuretics','近期利尿劑','select',1,['無','thiazide','loop','兩者/不明']],['medications','可能引起 SIADH 的藥物','checks',1,['無','SSRI/SNRI/TCA/MAOI','carbamazepine/oxcarbazepine','valproate/lamotrigine','cyclophosphamide/vinca/platinum','desmopressin','NSAID/opioid','其他'],1],['imaging','影像/病史線索','checks',1,['無','肺部感染/病灶','肺癌/惡性腫瘤','CNS 感染','中風/SAH/腦出血','頭部外傷','術後/疼痛/噁心','胸腺瘤/淋巴瘤'],1],['supportLabs','輔助檢驗','textarea',0,['可填 uric acid、BUN/urea、FE uric acid、cortisol、TSH/free T4、CXR/CT/MRI 摘要。'],1]]},
{id:'treatment',title:'治療策略與過度校正預防',short:'治療',desc:'根據症狀、慢性風險與病因，產生治療方向、監測頻率與過度校正警示。',hints:['嚴重症狀：考慮 3% hypertonic saline 150 mL over 20 min，重複至症狀改善或 Na 上升約 5 mmol/L。','慢性或不明時間：通常限制 24 小時總上升 <=10 mmol/L；高 ODS 風險常以 <=8 mmol/L/24 h。','Tolvaptan 適合部分 euvolemic/hypervolemic dilutional hyponatremia；不適合低容積、緊急快速矯正、無法口渴反應、無尿或與 hypertonic saline 併用。'],fields:[['odsRisk','ODS 高風險因子','checks',1,['無','Na <=105','低血鉀','酗酒','營養不良','晚期肝病'],1],['availableTherapy','可用治療','checks',1,['限水','3% 高張鹽水','loop diuretic','鹽錠/補溶質','urea','DDAVP','D5W','tolvaptan/Samsca','補充 cortisol/甲狀腺治療'],1],['tolvaptanContra','Tolvaptan 禁忌/限制','checks',1,['無','需緊急快速矯正嚴重神經症狀','低容積性低血鈉','無法反應口渴','無尿','肝病/肝損傷風險','強 CYP3A inhibitor','正在使用 hypertonic saline'],1],['monitoring','可執行監測強度','select',1,['ICU/高頻抽血 q2-4h','病房 q4-6h','門診/低頻監測','不確定']]]}
];
const $=s=>document.querySelector(s),state=JSON.parse(localStorage.hyponatremiaWizard||'{}');let cur=Number(localStorage.hyponatremiaStep||0);const arr=v=>Array.isArray(v)?v:[],save=()=>{localStorage.hyponatremiaWizard=JSON.stringify(state);localStorage.hyponatremiaStep=cur};
function full(f){let v=state[f[0]];return !f[3]||f[2]=='checks'?arr(v).length>0:v!==undefined&&String(v).trim()!==''}function done(i){return steps[i].fields.every(full)}function firstOpen(){let i=steps.findIndex((_,n)=>!done(n));return i<0?steps.length-1:i}
function classify(){let n=+state.serumNa;if(!Number.isFinite(n))return'尚未分類';if(n<125)return'profound hyponatremia';if(n<=129)return'moderate hyponatremia';if(n<135)return'mild hyponatremia';return'未達低血鈉定義'}
function tonicity(){let o=+state.serumOsm;if(!Number.isFinite(o))return'尚未判斷';return o>=275?'非低張性/偽性低血鈉需優先排除':'低張性低血鈉'}
function derive(){let n=+state.serumNa,g=+state.glucose;if(Number.isFinite(n)&&Number.isFinite(g))state.correctedNa=Math.round((n+2.4*((g-100)/100))*10)/10}
function etiology(){let so=+state.serumOsm,uo=+state.urineOsm,un=+state.urineNa,v=state.volumeStatus;if(Number.isFinite(so)&&so>=275)return'先處理/排除高張性或偽性低血鈉';if(Number.isFinite(uo)&&uo<=100)return'低尿滲透壓：考慮多喝水、低溶質攝取、beer potomania';if(v=='高容積/水腫')return'高容積性低血鈉：考慮 HF、肝硬化、腎病症候群、腎衰竭';if(v=='低容積')return Number.isFinite(un)&&un>30?'低容積且尿鈉高：考慮利尿劑、renal salt wasting、adrenal insufficiency、CSW':'低容積且尿鈉低：考慮 GI loss、第三空間、遠期利尿劑';if(v=='等容積'){if(state.adrenal&&state.adrenal!='已排除 adrenal insufficiency')return'需先排除 adrenal insufficiency';if(state.thyroid&&state.thyroid!='已排除嚴重低下')return'需先排除 severe hypothyroidism';if(state.diuretics&&state.diuretics!='無')return'近期利尿劑會干擾 SIADH 判讀';if(Number.isFinite(un)&&un>30&&Number.isFinite(uo)&&uo>100)return'符合 SIADH 型態，仍需結合排除條件'}return'資料不足或混合型，需要回到體液狀態與用藥病史'}
function plan(){let p=[],sev=state.symptomSeverity,e=etiology(),v=state.volumeStatus,high=arr(state.odsRisk).some(x=>x!='無'),contra=arr(state.tolvaptanContra).some(x=>x!='無');if(sev=='嚴重症狀')p.push('立即處理：3% hypertonic saline，目標先上升約 4-6 mmol/L 或症狀改善；高頻監測 Na。');else if(sev=='中度症狀')p.push('中度症狀：依病因治療，必要時考慮高張鹽水或住院嚴密監測。');else p.push('無嚴重症狀：優先完成病因鑑別並採 diagnosis-specific treatment。');if(v=='低容積')p.push('低容積：補充等張鹽水/容量，避免限水造成惡化。');if(v=='高容積/水腫')p.push('高容積：限水、限鹽、loop diuretic 與治療 HF/肝腎病因。');if(e.includes('SIADH'))p.push('SIADH：限水、提高溶質攝取，評估停用致病藥物；治療腫瘤/CNS/肺部誘因。');if(e.includes('低尿滲透壓'))p.push('低尿滲透壓：限制自由水，改善蛋白/鹽分等溶質攝取，避免快速水利尿造成過度校正。');if(contra)p.push('Tolvaptan：目前有禁忌或限制，除非重新評估，不宜作為本次主要策略。');else if(v=='等容積'||v=='高容積/水腫')p.push('Tolvaptan：可在 dilutional hyponatremia 且非緊急快速矯正情境下評估，需住院啟用並監測。');p.push('校正速率：'+(high||state.onset!='<48 小時'?'建議 24 小時上升 <=8 mmol/L；若非高風險，仍避免 >10 mmol/L/24h。':'急性可較積極，但仍需避免過度校正與頻繁監測。'));p.push('若過度校正：停止造成上升的治療，考慮 DDAVP clamp 與 D5W re-lowering。');return p}
function field(f){let [id,label,type,req,opts,wide]=f,box=document.createElement('label');box.className='field '+(wide?'full':'');box.innerHTML=`<span class="field-label">${label}${type=='number'&&opts[0]?` (${opts[0]})`:''} ${req?'<span class="required">*</span>':''}</span>`;let c;if(type=='select'){c=document.createElement('select');c.id=c.name=id;c.innerHTML='<option value="">請選擇</option>'+opts.map(o=>`<option>${o}</option>`).join('');c.value=state[id]||'';c.onchange=()=>upd(id,c.value)}else if(type=='checks'){c=document.createElement('div');c.className='choice-grid';opts.forEach(o=>{let l=document.createElement('label');l.className='choice';l.innerHTML=`<input name="${id}" type="checkbox" value="${o}" ${arr(state[id]).includes(o)?'checked':''}><span>${o}</span>`;l.querySelector('input').onchange=e=>{let n=arr(state[id]).filter(x=>x!=o);if(e.target.checked)n=o=='無'?['無']:n.filter(x=>x!='無').concat(o);upd(id,n)};c.appendChild(l)})}else if(type=='textarea'){c=document.createElement('textarea');c.id=c.name=id;c.value=state[id]||'';c.oninput=()=>upd(id,c.value,0)}else{c=document.createElement('input');c.id=c.name=id;c.type=type;c.value=state[id]||'';c.oninput=()=>upd(id,c.value,0);c.onblur=auto}box.appendChild(c);if(type=='textarea'&&opts[0]){let h=document.createElement('small');h.className='field-help';h.textContent=opts[0];box.appendChild(h)}return box}
function upd(id,val,go=1){state[id]=val;derive();save();paintSide();summary();validate();if(go)auto()}function auto(){if(done(cur)&&cur<steps.length-1)setTimeout(()=>{if(done(cur)){cur++;save();render()}},350)}
function paintSide(){let ol=$('#stepList');ol.innerHTML='';steps.forEach((s,i)=>{let li=document.createElement('li');li.className='step-item '+(i==cur?'is-current ':'')+(done(i)?'is-complete':'');li.innerHTML=`<span class="step-index">${done(i)?'✓':i+1}</span><span><strong>${s.short}</strong><span>${s.title}</span></span>`;li.onclick=()=>{if(i<=firstOpen()){cur=i;save();render()}};ol.appendChild(li)});$('#statusHeadline').textContent=classify();$('#statusDetail').textContent=`${tonicity()}；目前病因方向：${etiology()}`}
function summary(){let out=[`血鈉分類：${classify()}`,`校正鈉：${state.correctedNa?state.correctedNa+' mEq/L':'尚未計算'}`,`張力判讀：${tonicity()}`,`病因方向：${etiology()}`,'','關鍵資料',`- 症狀：${state.symptomSeverity||'未填'}；發生時間：${state.onset||'未填'}`,`- Serum Na/Osm/Glucose：${state.serumNa||'?'} / ${state.serumOsm||'?'} / ${state.glucose||'?'}`,`- Urine Osm/Na：${state.urineOsm||'?'} / ${state.urineNa||'?'}`,`- 體液狀態：${state.volumeStatus||'未填'}`,`- 影像/病史線索：${arr(state.imaging).join('、')||'未填'}`,'','治療提示',...plan().map(x=>'- '+x)];$('#liveSummary').textContent=out.join('\n')}
function validate(){let miss=steps[cur].fields.filter(f=>!full(f)).map(f=>f[1]),v=$('.validation'),n=$('#nextBtn');if(v)v.textContent=miss.length?'請先完成：'+miss.join('、'):'必填資料已完成，流程會自動前進。';if(n)n.disabled=!!miss.length}
function render(){let s=steps[cur];$('#stepTitle').textContent=s.title;$('#hintText').innerHTML='<ul>'+s.hints.map(h=>`<li>${h}</li>`).join('')+'</ul>';$('#wizardForm').innerHTML=`<div class="step-intro"><p>${s.desc}</p><div><span class="tag">${classify()}</span><span class="tag">${tonicity()}</span></div></div><div class="fields"></div><div class="validation"></div><div class="nav-row"><button class="text-button" type="button" id="backBtn">上一步</button><button class="primary-button" type="button" id="nextBtn">${cur==steps.length-1?'完成摘要':'下一步'}</button></div>`;let fs=$('.fields');s.fields.forEach(f=>fs.appendChild(field(f)));$('#backBtn').disabled=cur==0;$('#backBtn').onclick=()=>{if(cur>0){cur--;save();render()}};$('#nextBtn').onclick=()=>{if(done(cur)&&cur<steps.length-1){cur++;save();render()}};paintSide();summary();validate()}
$('#resetBtn').onclick=()=>{Object.keys(state).forEach(k=>delete state[k]);cur=0;save();render()};$('#copyBtn').onclick=async()=>navigator.clipboard.writeText($('#liveSummary').textContent);derive();render();
